{
  "hash": "f41757b1373713a15228e444ebf7e0fe",
  "result": {
    "markdown": "---\ntitle: \"Take-home Exercise 2: Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\ndate: \"2024-03-05\"\n---\n\n\n# Setting the Scene\n\n[Dengue Hemorrhagic Fever](https://www.cdc.gov/dengue/resources/denguedhf-information-for-health-care-practitioners_2009.pdf) (in short dengue fever) is one of the most widespread mosquito-borne diseases in the most tropical and subtropical regions. It is an acute disease caused by dengue virus infection which is transmitted by female Aedes aegypti and Aedes albopictus mosquitoes. In 2015, Taiwan had recorded the most severe dengue fever outbreak with more than 43,000 dengue cases and 228 deaths. Since then, the annual reported dengue fever cases were maintained at the level of not more than 200 cases. However, in 2023, Taiwan recorded 26703 dengue fever cases.\n\n## Objectives\n\nIn this exercise, we are curious to find out:\n\n-   if the distribution of dengue fever outbreak at Tainan City, Taiwan are independent from space and space and time.\n\n-   If the outbreak is indeed spatial and spatio-temporal dependent, then, you would like to detect where are the clusters and outliers, and the emerging hot spot/cold spot areas.\n\n## **The Task**\n\nThe specific tasks of this take-home exercise are as follows:\n\n-   Using appropriate function of **sf** and **tidyverse**, preparing the following geospatial data layer:\n\n    -   a study area layer in sf polygon features. It must be at village level and confined to the D01, D02, D04, D06, D07, D08, D32 and D39 counties of Tainan City, Taiwan.\n\n    -   a dengue fever layer within the study area in sf point features. The dengue fever cases should be confined to epidemiology week 31-50, 2023.\n\n    -   a derived dengue fever layer in [spacetime s3 class of sfdep](https://sfdep.josiahparry.com/articles/spacetime-s3). It should contain, among many other useful information, a data field showing number of dengue fever cases by village and by epidemiology week.\n\n-   Using the extracted data, perform global spatial autocorrelation analysis by using [sfdep methods](https://is415-gaa-tskam.netlify.app/in-class_ex/in-class_ex05/in-class_ex05-glsa).\n\n-   Using the extracted data, perform local spatial autocorrelation analysis by using [sfdep methods](https://r4gdsa.netlify.app/chap10.html).\n\n-   Using the extracted data, perform emerging hotspot analysis by using [sfdep methods](https://is415-gaa-tskam.netlify.app/in-class_ex/in-class_ex05/in-class_ex05-ehsa).\n\n-   Describe the spatial patterns revealed by the analysis above.\n\n# Data Used\n\n| Data Set           | Description                                                                                                      | Source                                                                                                              |\n|--------------------|--------------------------|--------------------------|\n| `TAIWAN_VILLAGE`   | Geospatial data of the village boundary of Taiwan in ESRI shapefile and in Taiwan's Geographic Coordinate System | [Historical map data of the village boundary: TWD97 longitude and latitude](https://data.gov.tw/en/datasets/130549) |\n| `Dengue_Daily.csv` | Aspatial data of reported dengue cases in Taiwan since 1998.                                                     | [Dengue Daily Confirmed Cases Since 1998](https://data.cdc.gov.tw/en/dataset/dengue-daily-determined-cases-1998)    |\n\n# **Installing and Loading the R packages**\n\nThe R packages used in this exercise are:\n\n-   **sf:** this packages provides an efficient framework designed for importing, managing and processing vector-based geospatial data in R\n\n-   **spdep** will be used to compute spatial weights, global and local spatial autocorrelation statistics\n\n-   **tmap:** provides functions for plotting cartographic quality static point patterns maps or interactive maps by using Leaflet API\n\n-   **tidyverse:** a collection of R packages designed to facilitate and streamline the process of data analysis and manipulation in R\n\n-   **plotly:** to create wide range of graphs and charts and enables interactive, dynamic data visualization\n\n\\\nThe following code chunk accomplishes the following objectives:\n\n1.  Compiles a list of essential R packages.\n\n2.  Verifies whether these R packages are installed.\n\n3.  Installs any missing packages using RStudio.\n\n4.  Loads the packages into the R environment for use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spded, sfdep, tmap, tidyverse, plotly, Kendall)\n```\n:::\n\n\n# Import the geospatial data\n\nIn this section, we will use **st_read()** to read the Taiwan boundary layer as a simple features data frame. We can convert it to other objects later on if necessary!\n\nIn the code below, `dsn` specifies the filepath where the dataset is located and `layer` provides the filename of the dataset excluding the file extension.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntainan <- st_read(dsn = \"data/geospatial\", \n                 layer = \"TAINAN_VILLAGE\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `TAINAN_VILLAGE' from data source \n  `C:\\jaymieseet\\IS415-GAA-JS\\Take-home_Ex\\Take-home_Ex02\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 649 features and 10 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 120.0269 ymin: 22.88751 xmax: 120.6563 ymax: 23.41374\nGeodetic CRS:  TWD97\n```\n:::\n:::\n\n\n## Geospatial Data Pre-processing\n\n### Inspecting the Projected Coordinate System\n\nAs this data is situated in Taiwan, the appropriate Geographic Coordinate System is EPSG::3824 (TWD97), which is the national Projected Coordinate System for Taiwan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(tainan)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoordinate Reference System:\n  User input: TWD97 \n  wkt:\nGEOGCRS[\"TWD97\",\n    DATUM[\"Taiwan Datum 1997\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    USAGE[\n        SCOPE[\"Horizontal component of 3D system.\"],\n        AREA[\"Taiwan, Republic of China - onshore and offshore - Taiwan Island, Penghu (Pescadores) Islands.\"],\n        BBOX[17.36,114.32,26.96,123.61]],\n    ID[\"EPSG\",3824]]\n```\n:::\n:::\n\n\nLet's view the dataset columns with the code below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(tainan,1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple feature collection with 1 feature and 10 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 120.2695 ymin: 22.93251 xmax: 120.2905 ymax: 22.96072\nGeodetic CRS:  TWD97\n     VILLCODE COUNTYNAME TOWNNAME VILLNAME     VILLENG COUNTYID COUNTYCODE\n1 67000280002     臺南市   歸仁區   六甲里 Liujia Vil.        D      67000\n  TOWNID TOWNCODE NOTE                       geometry\n1    D33 67000280 <NA> POLYGON ((120.2725 22.95868...\n```\n:::\n:::\n\n\nThis dataset contains information on the towns and village names in Taiwan, which includes the village and town names, ID and codes.Each row is also tagged to a polygon geometry data.\n\nOur analysis at the village level is confined to the D01, D02, D04, D06, D07, D08, D32 and D39 counties of Tainan City, Taiwan. Hence, let's filter the data to only retain information of the counties we want with the code chunk below:\n\n-   Create a vector **`town_ids`** containing the town IDs of interest, namely \"D01\", \"D02\", \"D04\", \"D06\", \"D07\", \"D08\", \"D32\", and \"D39\"\n\n-   Create a subset of the dataframe **`tainan`**. It selects rows where the **`TOWNID`** column matches any of the town IDs specified in the **`town_ids`** vector. The resulting subset is stored in the variable **`tn_counties`**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntown_ids <- c(\"D01\", \"D02\", \"D04\", \"D06\", \"D07\", \"D08\", \"D32\", \"D39\")\ntn_counties <- subset(tainan, TOWNID %in% town_ids)\ntn_counties\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple feature collection with 258 features and 10 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 120.0627 ymin: 22.89401 xmax: 120.2925 ymax: 23.09144\nGeodetic CRS:  TWD97\nFirst 10 features:\n      VILLCODE COUNTYNAME TOWNNAME VILLNAME       VILLENG COUNTYID COUNTYCODE\n2  67000350032     臺南市   安南區   青草里  Qingcao Vil.        D      67000\n18 67000270011     臺南市   仁德區   保安里   Bao'an Vil.        D      67000\n66 67000370005     臺南市   中西區   赤嵌里  Chihkan Vil.        D      67000\n67 67000330004     臺南市     南區   大成里  Dacheng Vil.        D      67000\n68 67000350028     臺南市   安南區   城北里 Chengbei Vil.        D      67000\n69 67000350030     臺南市   安南區   城南里 Chengnan Vil.        D      67000\n73 67000370009     臺南市   中西區   法華里    Fahua Vil.        D      67000\n74 67000350017     臺南市   安南區   海南里   Hainan Vil.        D      67000\n75 67000350049     臺南市   安南區   國安里   Guo'an Vil.        D      67000\n76 67000350018     臺南市   安南區   溪心里    Xixin Vil.        D      67000\n   TOWNID TOWNCODE NOTE                       geometry\n2     D06 67000350 <NA> POLYGON ((120.1176 23.08387...\n18    D32 67000270 <NA> POLYGON ((120.2304 22.93544...\n66    D08 67000370 <NA> POLYGON ((120.2012 22.99966...\n67    D02 67000330 <NA> POLYGON ((120.1985 22.98147...\n68    D06 67000350 <NA> POLYGON ((120.1292 23.06512...\n69    D06 67000350 <NA> POLYGON ((120.1246 23.06904...\n73    D08 67000370 <NA> POLYGON ((120.2094 22.98452...\n74    D06 67000350 <NA> POLYGON ((120.175 23.02218,...\n75    D06 67000350 <NA> POLYGON ((120.1866 23.02766...\n76    D06 67000350 <NA> POLYGON ((120.1834 23.06086...\n```\n:::\n:::\n\n\nThe main columns that we will use in the analysis would be the VILLNAME and TOWNNAME, so let's check whether there are any missing values that we have to deal with before we proceed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(tn_counties$VILLNAME == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(tn_counties$TOWNNAME == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nThere are no missing values so we are good to move on!\n\nLet us plot the tn_counties data!\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(tn_counties) +\n  tm_borders()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n# Import aspatial data\n\nNext, we will import the aspatial dataset with read_csv().\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_cases <- read_csv(\"data/aspatial/Dengue_Daily.csv\")\n```\n:::\n\n\nLet's inspect this data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(dengue_cases)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 26\n  發病日     個案研判日 通報日     性別  年齡層 居住縣市 居住鄉鎮 居住村里\n  <date>     <chr>      <date>     <chr> <chr>  <chr>    <chr>    <chr>   \n1 1998-01-02 None       1998-01-07 男    40-44  屏東縣   屏東市   None    \n2 1998-01-03 None       1998-01-14 男    30-34  屏東縣   東港鎮   None    \n3 1998-01-13 None       1998-02-18 男    55-59  宜蘭縣   宜蘭市   None    \n4 1998-01-15 None       1998-01-23 男    35-39  高雄市   苓雅區   None    \n5 1998-01-20 None       1998-02-04 男    55-59  宜蘭縣   五結鄉   None    \n6 1998-01-22 None       1998-02-19 男    20-24  桃園市   蘆竹區   None    \n# ℹ 18 more variables: 最小統計區 <chr>, 最小統計區中心點X <chr>,\n#   最小統計區中心點Y <chr>, 一級統計區 <chr>, 二級統計區 <chr>,\n#   感染縣市 <chr>, 感染鄉鎮 <chr>, 感染村里 <chr>, 是否境外移入 <chr>,\n#   感染國家 <chr>, 確定病例數 <dbl>, 居住村里代碼 <chr>, 感染村里代碼 <chr>,\n#   血清型 <chr>, 內政部居住縣市代碼 <chr>, 內政部居住鄉鎮代碼 <chr>,\n#   內政部感染縣市代碼 <chr>, 內政部感染鄉鎮代碼 <chr>\n```\n:::\n:::\n\n\nThis dataset contains the information of each dengue case, including the onset date, as well as the X and Y coordinates of each case:\n\n-   發病日: Onset date\n\n-   最小統計區中心點X: x-coordinate\n\n-   最小統計區中心點Y: y-coordinate\n\n## Aspatial Data Wrangling\n\nSince the column names are in chinese, we should rename the columns that we will be using for easy reference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_cases <- dengue_cases %>% rename(\"onset_date\" = \"發病日\",\n                      \"x_coord\" = \"最小統計區中心點X\",\n                      \"y_coord\" = \"最小統計區中心點Y\",\n                      \"county\" = \"居住縣市\",\n                      \"VILLNAME\" = \"居住村里\",\n                      \"TOWNNAME\" = \"居住鄉鎮\")\ncolnames(dengue_cases)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"onset_date\"         \"個案研判日\"         \"通報日\"            \n [4] \"性別\"               \"年齡層\"             \"county\"            \n [7] \"TOWNNAME\"           \"VILLNAME\"           \"最小統計區\"        \n[10] \"x_coord\"            \"y_coord\"            \"一級統計區\"        \n[13] \"二級統計區\"         \"感染縣市\"           \"感染鄉鎮\"          \n[16] \"感染村里\"           \"是否境外移入\"       \"感染國家\"          \n[19] \"確定病例數\"         \"居住村里代碼\"       \"感染村里代碼\"      \n[22] \"血清型\"             \"內政部居住縣市代碼\" \"內政部居住鄉鎮代碼\"\n[25] \"內政部感染縣市代碼\" \"內政部感染鄉鎮代碼\"\n```\n:::\n:::\n\n\nIn this analysis, we want to study the distribution of dengue fever outbreak at Tainan city that is within the epidemiology week 31-50, 2023.\n\nThe epidemiology week is a standardized way of counting weeks in epidemiological surveillance and reporting. It provides a common reference point for reporting and analysing disease outbreaks, trends and surveillance data. This helps public health authorities to identify seasonal patterns, detect outbreaks and monitor the effectiveness of interventions.\n\nTherefore, we will extract the cases that falls within the period of epidemiology week 31-50 in 2023. From a search online, I found that the weeks in Taiwan starts from Sunday, thus the dates that fall within these 20 weeks are 30th July 2023 to 16th December 2023.\n\nThe code below does the following things:\n\n1.  It adds two new columns to the **`dengue_cases`** dataframe:\n\n    -   The **`year`** column is created by extracting the year from the **`onset_date`** column and converting it into a factor variable.\n\n    -   The **`week`** column is created by extracting the week number from the **`onset_date`**.\n\n2.  It filters the rows in the **`dengue_cases`** dataframe based on the **`onset_date`**. Only rows where the **`onset_date`** falls between \"2023-07-30\" and \"2023-12-16\" (inclusive) are retained.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_cases <- dengue_cases %>%\n  mutate(year = factor(year(onset_date)),\n         week = week(onset_date)) %>%\n  filter(onset_date >= \"2023-07-30\" & onset_date <= \"2023-12-16\")\n```\n:::\n\n\nWe should inspect the data to make sure there are no missing data in the table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dengue_cases$x_coord == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 14\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dengue_cases$y_coord == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 14\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dengue_cases$VILLNAME == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2600\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dengue_cases$TOWNNAME == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nUpon inspecting the data, there are missing values in the X Y coordinate fields, as well as the VILLNAME field. There are a few ways we can deal with this. One common approach to handling missing values is to impute them with the mean or median values derived from the existing data. However, when dealing with coordinates, this approach may not be ideal. The mean or median coordinates may not accurately represent the missing locations, particularly in areas with diverse geography or uneven distribution of cases. Imputing with mean or median coordinates could potentially lead to misleading spatial analysis results, as it might place missing cases in locations where they do not actually exist.\n\nThus, a more feasible way to deal with the missing values would be to exclude these rows with missing coordinates from the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_cases <- dengue_cases %>%\n                 filter(x_coord != \"None\", y_coord != \"None\", \n                        VILLNAME != \"None\")\n```\n:::\n\n\nNow, let's check the fields to ensure all the rows with null values are removed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dengue_cases$x_coord == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dengue_cases$y_coord == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dengue_cases$VILLNAME == \"None\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nWhen reviewing the dengue_cases dataset, we can see that the X and Y coordinate fields are currently represented in character format. To integrate the data frame into an sf data frame for spatial analysis, it's necessary to convert these fields into numeric data types.\n\n![](images/clipboard-3012718302.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert character fields to numeric\ndengue_cases$x_coord <- as.numeric(dengue_cases$x_coord)\ndengue_cases$y_coord <- as.numeric(dengue_cases$y_coord)\n```\n:::\n\n\n![](images/clipboard-1626234782.png)\n\nNow we can convert it into a sf object!\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_sf <- st_as_sf(dengue_cases,\n                      coords = c(\"x_coord\",\"y_coord\"),\n                      crs = st_crs(tn_counties))\n```\n:::\n\n\nWhen we look at the data in tn_counties, we will see that the VILLNAME column are not unique values and there are a few villages of the same name but located in a different town. This might cause problems when we are joining the two tables together later on since there will not be a one-to-one join, causing inaccurate results.\n\nTo circumvent this challenge, we can concatenate the TOWNNAME values and VILLNAME values to make a TOWNVILL column, to act as the unique identifier of a specific location.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntn_counties <- tn_counties %>%\n  mutate(TOWNVILL = paste(TOWNNAME, VILLNAME, sep = \"_\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_cases <- dengue_cases %>%\n  mutate(TOWNVILL = paste(TOWNNAME, VILLNAME, sep = \"_\"))\n```\n:::\n\n\nNow, lets quickly plot both datas to visualise the cases on the map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(tn_counties) +\n  tm_polygons(\"TOWNID\") +\ntm_shape(dengue_sf) +\n  tm_dots(col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nNext, we can perform a left join to join both data frames into 1, which is tainan_dengue using the code below. This will result in a lot of columns being made, so we can use the select function to select the specific columns that we would like to keep for our subsequent analysis.\n\n-   Left join, from the dplyr package, between the **`tn_counties`** and **`dengue_cases`** data frames using the **`TOWNVILL`** column as the key for joining\n\n-   After the join operation, it selects specific columns from the resulting data frame, including column 11 and columns 38 to 40 using select() from dplyr package\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntainan_dengue <- left_join(tn_counties, dengue_cases, by = c(\"TOWNVILL\")) %>%\n  select(11, 30, 38:40)\n```\n:::\n\n\nNext with this joined data, we want to generate the summarized total number of dengue observations within each town and village boundary.\n\nWe can do so by using several functions from the dplyr package:\n\n-   Data frame **`tainan_dengue`** is grouped by the **`TOWNVILL`** column\n\n-   Within each group, calculate the total number of cases using the sum of 確定病例數 and select the first geometry associated with each group using **`first(geometry)`**\n\n-   Remove the grouping structure, ensuring that the resulting data frame is not grouped anymore\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntainan_dengue_df <- tainan_dengue %>%\n  group_by(TOWNVILL) %>%\n  summarize(total_cases = sum(確定病例數), geometry = first(geometry)) %>%\n  ungroup()\n```\n:::\n\n\nSince we did a left join, there is a possibility that not all villages that are present in tn_counties have dengue cases reported, which will cause null values in the total_cases column.\n\nWe can check for the null values using is.na().\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(tainan_dengue_df$total_cases))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 33\n```\n:::\n:::\n\n\nWe can see that there are 33 null values. Removing the rows with the null values might cause problems in the further analysis. In order to avoid that, we can replace the null values with 0 as a place holder using replace().\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntainan_dengue_df$total_cases <- replace(tainan_dengue_df$total_cases, is.na(tainan_dengue_df$total_cases), 0)\n```\n:::\n\n\nWe can see that there are no more null values!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(tainan_dengue_df$total_cases))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nSince the data preparation is done, let's save it\n\n# Global Spatial Autocorrelation Analysis\n\nIn this section, we will compute Global Moran's I of dengue cases at village level by using global_moran() of sfdep package.\n\nAfter all the data preparation, we can now move on to the Global Spatial Autocorrelation Analysis. Firstly, let's go through what this analysis entails.\n\nSpatial Autocorrelation tool measure the spatial autocorrelation based on both feature locations and feature values simultaneously. The spatial autocorrelation refers to how both the geographic proximity (locations) and attribute similarities (values) of features unfluence each other. It examines whether nearby features tend to have similar attribute values and whether this similarity is statictically significant.\n\nThe main objective of this analysis is to apply appropriate spatial statistical methods to discover if the cases are evenly distributed and if not, are there signs of spatial clustering and where are these clusters?\n\nIn this analysis, we are using Moran's I, which is a statistic that quantifies the spatial clustering of values in a dataset.It is calculated by comparing the values of a variable at each location with the values of the variable at neighbouring locations, resulting in Moran I's statistic ranging from -1 to 1.\n\nBefore we start the analysis, let's plot choropleth maps to show the distribution of dengue cases in Tainan using qtm() of tmap package.\n\n-   The first map uses equal interval classification, dividing the range of total cases into 5 equal intervals, each with a distinct color representing the intensity of dengue cases.\n\n-   The second map employs quantile classification, which divides the data into 5 classes with approximately an equal number of observations in each class, providing insight into the distribution of cases across different quantiles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(tainan_dengue_df) +\n  tm_fill(\"total_cases\",\n          n = 5,\n          style = \"equal\") +\n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"Equal interval classification\")\n\nquantile <- tm_shape(tainan_dengue_df) +\n  tm_fill(\"total_cases\",\n          n = 5,\n          style = \"quantile\") +\n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"Equal quantile classification\")\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n## Computing Contiguitiy Spatial Weights\n\nBefore calculating the global spatial autocorrelation statistics, we must create spatial weights for the study area. Spatial weights establish the connections between neighboring geographic units (i.e. villages) within the study area, defining their neighborhood relationships.\n\nWe can pass a \"queen\" argument that takes True or False as options. If not specified, the default is set to TRUE, which will return a list of first order neighbours using the Queen criteria. This criteria means that if even a single point on the boundary of one unit coincides with a point on the boundary of another unit, they are considered neighbours.\n\n-   **`nb = st_contiguity(geometry)`**: Computes spatial contiguity weights based on the geometry column, determining which observations (geographic units) share a border\n\n-   st_weight():\n\n    -   style: Caluculates spatial weights based on the contiguity weights (\"nb\") using specified style \"W\"\n\n    -   .before = 1: Specifies that the new columns ('nb' and 'wt') should be inserted at the first position in the dataset\n\n::: callout-note\nThere are different styles to define the spatial weight, which determine the strength of relationships between neighbouring geographic units. The default that we have used here is \"W\", which is \"row standardized weights\".\n\nThere are other values: \"B\", “C”, “U”, “minmax”, and “S”. Each option has its own advantages and is suitable for different types of analyses and datasets, depending on the nature of spatial relationships and the objectives of the analysis.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- tainan_dengue_df %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb,\n                         style = \"W\"),\n         .before = 1) \n```\n:::\n\n\n## Computing Global Moran'I\n\nThis code computes the Global Moran's I statistic, which is a measure of spatial autocorrelation indicating whether the spatial pattern is clustered, dispersed or randomly distributed.\n\n**`global_moran()`**: This function calculates the Global Moran's I statistic. It takes three main arguments:\n\n-   `x`: The variable for which spatial autocorrelation is being measured (in this case, `wm_q$total_cases`).\n\n-   `listw`: The spatial weights matrix, which defines the spatial relationships between observations (in this case, `wm_q$nb`).\n\n-   `weights`: The type of spatial weights to be used (in this case, `wm_q$wt`)\n\nWe can use the glimpse() function to display a concise summary of the `moranI` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_q$total_cases,\n                       wm_q$nb,\n                       wm_q$wt)\nglimpse(moranI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 2\n $ I: num 0.42\n $ K: num 5.58\n```\n:::\n:::\n\n\n## Performing Global Moran's I test\n\nThe `global_moran_test()` conducts a hypothesis test for global spatial autocorrelation to assess the statistical significance of the Global Moran's I statistic.\n\nThe hypotheses that we will be testing is:\n\n1.  Null hypothesis (H0) states that there is no spatial autocorrelation present in the dataset (dengue cases is randomly distributed across space)\n\n2.  Alternative hypothesis (H1) states that there is spatial autocorrelation present in the dataset (dengue cases exhibits clustering or dispersion tendencies)\n\n::: callout-note\n-   The default for `alternative` argument is “two.sided”. Other supported arguments are “greater” or “less”. randomization, and\n\n-   By default the `randomization` argument is **TRUE**. If FALSE, under the assumption of normality.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test(wm_q$total_cases,\n                       wm_q$nb,\n                       wm_q$wt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 11.538, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.419567083      -0.003891051       0.001347083 \n```\n:::\n:::\n\n\nFrom the results of this test, the p-value calculated is less than 2.2e-16, which is significantly smaller than the significance level of 0.05. This indicates strong evidence against the null hypothesis of spatial randomness. Therefore, we reject the null hypothesis and conclude that the observed spatial pattern is highly unlikely to occur by random chance alone, with 95% confidence. Since the alternative hypothesis is \"greater\", suggesting that there is positive spatial autocorrelation (clustering) in the data.\n\nThe value of Moran's I statistic is 0.4196. This value ranges between -1 and 1. Hence, a positive value indicates positive value suggests that similar values of the variable being analyzed tend to be clustered together.\n\n## Performing Global Moran'I Permutation Test\n\n**`set.seed(1234)`** sets the random number generator's seed to a specific value, in this case, 1234. This ensures that when you generate random numbers using functions like **`runif()`**, **`rnorm()`**, or other random number generators in R, you get the same sequence of random numbers every time you run your code.\n\nThis is useful for reproducibility purposes, especially when conducting simulations or experiments that involve randomness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n\n\nNext, `global_moran_perm()` is used to perform Monte Carlo simulation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(wm_q$total_cases,\n                       wm_q$nb,\n                       wm_q$wt,\n                  nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = 0.41957, observed rank = 100, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n:::\n:::\n\n\nThe statistical report above shows that the p-value is smaller than alpha value of 0.05. Thus, we have enough statistical evidence to reject the null hypothesis that the dengue cases resemble random distribution. Also, as explained previously, the Moran's I statistics is greater than 0, which we can infer that the spatial distribution shows signs of clustering.\n\n# Computing Local Moran's I\n\nIn this section, we will compute Local Moran's I of dengue cases at village level by using local_moran() of sfdep package. It computes Ii values, given a set of zi values and a listw object providing neighbour weighting information for the polygon associated with the zi values.\n\nLocal Moran's I is a metric for spatial autocorrelation, assessing clustering or dispersion within geographic data at the individual feature or location level. In contrast to global Moran's I, which offers a single summary for the entire dataset, Local Moran's I computes spatial autocorrelation values for each feature or location independently. This will provide further insights into the spatial distribution patterns at a local level, enabling the identification of spatial clusters and outliers with the dataset.\n\nTo conduct Local Moran's I, we must first create a LISA (Local Indicators of Spatial Association) object, which is a representation of spatial autocorrelation analysis results at the local level. It provides information regarding the extent of spatial grouping or spread for each specific feature or location within a geographical dataset.\n\nThe code below calculates Local Moran's I statistic for each observation in the dataset.\n\n1.  The **`local_moran()`** function computes the local Moran's I statistic for the variable **`total_cases`** using the spatial weights (**`nb`**) and the weights matrix (**`wt`**). The **`nsim`** parameter specifies the number of permutations for the null hypothesis.\n\n2.  The results are then added as a new column named **`local_moran`** to the dataframe **`wm_q`**.\n\n3.  The **`unnest()`** function expands the results of the **`local_moran`** column into separate rows, making them accessible for further analysis and visualization.\n\nThe output of `local_moran()` is a sf data.frame containing the columns ii, eii, var_ii, z_ii, p_ii, p_ii_sim, and p_folded_sim.\n\n-   ii: local moran statistic\n\n-   eii: expectation of local moran statistic; for localmoran_permthe permutation sample means\n\n-   var_ii: variance of local moran statistic; for localmoran_permthe permutation sample standard deviations\n\n-   z_ii: standard deviate of local moran statistic; for localmoran_perm based on permutation sample means and standard deviations p_ii: p-value of local moran statistic using pnorm(); for localmoran_perm using standard deviatse based on permutation sample means and standard deviations p_ii_sim: For `localmoran_perm()`, `rank()` and `punif()` of observed statistic rank for \\[0, 1\\] p-values using `alternative=` -p_folded_sim: the simulation folded \\[0, 0.5\\] range ranked p-value (based on https://github.com/pysal/esda/blob/4a63e0b5df1e754b17b5f1205b cadcbecc5e061/esda/crand.py#L211-L213)\n\n-   skewness: For `localmoran_perm`, the output of e1071::skewness() for the permutation samples underlying the standard deviates\n\n-   kurtosis: For `localmoran_perm`, the output of e1071::kurtosis() for the permutation samples underlying the standard deviates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- wm_q %>% \n  mutate(local_moran = local_moran(\n    total_cases, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n### **Visualising Local Moran’s I**\n\nThe code below plot the Local Moran's I values onto a map using functions in tmap package.\n\n-   Set plotting mode to \"plot\" and create a thematic map using the LISA object\n\n-   tm_fill(): Maps the local Moran's I values ('ii')\n\n-   Sets zoom limits for viewing and adjusts the layout with a main title\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(lisa) +\n  tm_fill(\"ii\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"local Moran's I of Total Dengue Cases\",\n            main.title.size = 0.8)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nThe 'ii' values in a local Moran's I analysis represent the local spatial autocorrelation coefficients for each village in the dataset. These coefficients indicate whether a particular feature is part of a cluster of similar values surrounded by similar values (high-high), a cluster of dissimilar values surrounded by dissimilar values (low-low), an outlier with high values surrounded by low values (high-low), or an outlier with low values surrounded by high values (low-high).\n\n-   Positive values (high-high and low-low) indicate clustering or similarity.\n\n-   Negative values (high-low and low-high) indicate dispersion or dissimilarity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(lisa) +\n  tm_fill(\"p_ii_sim\") + \n  tm_borders(alpha = 0.5) +\n   tm_layout(main.title = \"p-value of local Moran's I\",\n            main.title.size = 0.8)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n### **Visualising p-value of Local Moran’s I**\n\nThis map visualizes the p-values (\"p_ii_sim\" field) of the local Moran's I statistic for each spatial unit in the dataset. It helps to identify significant spatial clusters or outliers based on the values of the local Moran's I. Areas with low p-values indicate significant spatial clustering, while high p-values suggest spatial randomness.\n\n-   Set plotting mode to \"plot\" using `tmap_mode(\"plot\")`.\n\n-   Use `tm_shape(lisa)` to specify the shapefile to be plotted.\n\n-   Fill the polygons with values from the variable 'p_ii_sim' using `tm_fill(\"p_ii_sim\")`.\n\n-   Add borders to the polygons with specified transparency using `tm_borders(alpha = 0.5)`.\n\n-   Set the main title of the map using `tm_layout(main.title = \"p-value of local Moran's I\", main.title.size = 0.8)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_fill(\"p_ii\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of local Moran's I\",\n            main.title.size = 0.8)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nFor effective comparison, we can plot the both maps side by side. By examining both maps together, we can identify areas of significant spatial clustering or dispersion and determine whether these patterns are statistically meaningful.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa) +\n  tm_fill(\"ii\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"local Moran's I of Dengue Cases\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(lisa) +\n  tm_fill(\"p_ii\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of local Moran's I\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nHaving a high local Moran's I value and a very significant p-value indicates strong evidence of spatial clustering and spatial autocorrelation in the data.\n\n-   The high local Moran's I value suggests that there are local clusters of similar values (either high or low) in the dataset.\n\n-   The very significant p-value indicates that the observed spatial pattern is highly unlikely to occur by random chance alone, suggesting that the clustering is statistically significant.\n\nOne of such area we can identify from the maps are right in the central area of Tainan, where there is a high local Moran's I value and also significant p-value. In the north-western area of the maps there is also quite a big area with positive local Moran's I value, with a significant p-value. Even though the local Moran's I value is not high, this could still suggest neighbouring locations with similar attribute values are clustered together.\n\nHowever, that is not true for the area in the east of Tainan. As we can see from the left map, there is another small area that is dark green, but on the p-value map, it is not significant. This may suggest that there might be a noticeable level of spatial autocorrelation (neighbouring areas tend to have similar values), but the non-significant p-value will suggest that this could be due to random chance.\n\n## Visualising LISA Map\n\nThe LISA map categorizes spatial data to identify outliers and clusters, including High-Low and Low-High outliers, as well as High-High and Low-Low clusters. It's generated by integrating local Moran's I values and their associated p-values for different geographic areas.\n\nWithin the LISA spatial dataframe, there are three fields representing LISA categories: mean, median, and pysal. Generally, the mean classification is utilized for interpretation and analysis, as illustrated in the code below.\n\nThis code filters the LISA objects to include only those with significant p-values. It then creates a map using tmap, plotting all LISA objects but only filling the LISA objects that have statistically significant results based on their p-values. These significant objects are highlighted on the map, indicating where spatial clustering or outliers are present with a 95% confidence level.\n\nThe mean value is then used to help identify whether the clustering is characterized by high-high (similar high values clustered together) or low-low (similar low values clustered together) patterns, or if outliers are present (high-low or low-high patterns).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_sig <- lisa  %>%\n  filter(p_ii < 0.05)\ntmap_mode(\"plot\")\ntm_shape(lisa) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig) +\n  tm_fill(\"mean\") + \n  tm_borders(alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nFrom this map, we can now clearly see where are the clusters of high number of cases and clusters of low number of cases.\n\nThe central area of Tainan stands out as the most significant location with multiple high-high clusters, spanning across approximately 20 villages. Several factors may contribute to this concentrated pattern, including population density, environmental conditions, and human activities.\n\nFor instance, a comprehensive study on the [Space-Time Analysis of the Dengue outbreak in Tainan](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5876941/) revealed a major hotspot in the West-Central district during September. This district, characterized by its ancient buildings and high population density, emerges as a focal point for Dengue clusters. The age of the community might contribute to a lower awareness of the outbreak and preventive measures among the older population. Moreover, the high population density amplifies the impact of individual behaviors, potentially facilitating the spread of the virus from one person to another.\n\nIn essence, the presence of multiple high-high clusters in the central area suggests a complex interplay of demographic, environmental, and cultural factors that contribute to the spatial dynamics of the Dengue outbreak in Tainan.\n\n# **Hot Spot and Cold Spot Area Analysis (HCSA)**\n\nHCSA uses spatial weights to identify locations of statistically significant hot spots and cold spots in an spatially weighted attribute that are in proximity to one another based on a calculated distance. The analysis groups features when similar high (hot) or low (cold) values are found in a cluster. The polygon features usually represent administration boundaries or a custom grid structure.\n\nWhile both HCSA and Local Moran's I analysis both aim to identify spatial clustering patterns, HCSA specifically targets identifying hot spots and cold spots within a spatial dataset based on proximity and value similarity, whereas Local Moran's I analysis examines the spatial autocorrelation of individual features to identify local clusters of similarity or dissimilarity.\n\n## **Computing Local Gi\\* statistics**\n\nAs usual, we will need to derive a spatial weight matrix before we can compute local Gi\\* statistics. Code chunk below will be used to derive a spatial weight matrix by using sfdep functions and tidyverse approach.\n\n-   Calculate spatial weights for an inverse distance weighted interpolation (IDW) analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_idw <- tainan_dengue_df %>%\n  mutate(nb = st_contiguity(geometry),\n         wts = st_inverse_distance(nb, geometry,\n                                   scale = 1,\n                                   alpha = 1),\n         .before = 1)\n```\n:::\n\n\nNow, we will perform HCSA using the calculated spatial weights\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA <- wm_idw %>% \n  mutate(local_Gi = local_gstar_perm(\n    total_cases, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_Gi)\nHCSA\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple feature collection with 258 features and 14 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 120.0627 ymin: 22.89401 xmax: 120.2925 ymax: 23.09144\nGeodetic CRS:  TWD97\n# A tibble: 258 × 15\n   gi_star cluster    e_gi    var_gi std_dev p_value p_sim p_folded_sim skewness\n     <dbl> <fct>     <dbl>     <dbl>   <dbl>   <dbl> <dbl>        <dbl>    <dbl>\n 1 -1.59   Low     0.00349   1.29e-6 -1.46    0.143   0.18         0.09   0.471 \n 2  0.0390 High    0.00408   1.87e-6 -0.0961  0.923   0.92         0.46   0.349 \n 3 -1.63   Low     0.00333   1.69e-6 -1.31    0.190   0.14         0.07   1.30  \n 4 -1.23   Low     0.00332   1.75e-6 -0.871   0.383   0.36         0.18   0.202 \n 5 -1.90   Low     0.00342   1.40e-6 -1.68    0.0920  0.06         0.03   0.512 \n 6 -2.00   Low     0.00344   1.40e-6 -1.82    0.0692  0.06         0.03  -0.0488\n 7 -0.569  Low     0.00344   1.81e-6 -0.264   0.792   0.88         0.44   0.666 \n 8 -1.11   Low     0.00384   1.54e-6 -1.06    0.288   0.28         0.14   0.553 \n 9 -1.92   Low     0.00332   1.63e-6 -1.50    0.134   0.1          0.05   0.473 \n10 -2.37   Low     0.00320   1.82e-6 -2.13    0.0335  0.04         0.02   0.229 \n# ℹ 248 more rows\n# ℹ 6 more variables: kurtosis <dbl>, nb <nb>, wts <list>, TOWNVILL <chr>,\n#   total_cases <dbl>, geometry <POLYGON [°]>\n```\n:::\n:::\n\n\n## Visualising Local HCSA\\*\n\nThe code below generates 2 thematic map based on the HCSA.The first map shows the values of the GI\\* statistic calculated for dengue fever cases in Tainan. The second map visualizes the p-value associated with the Gi\\* statistic calculated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Dengue Cases\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA) +\n  tm_fill(\"p_value\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n## Visualising Hot Spot and Cold Spot Areas\n\nSimilarly, this map plots the the significant (i.e. p-values less than 0.05) hot spot and cold spot areas by using appropriate tmap functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_sig <- HCSA  %>%\n  filter(p_sim < 0.05)\ntmap_mode(\"plot\")\ntm_shape(HCSA) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nPositive Gi\\* values indicate that a feature has high values and is surrounded by other features with similarly high values, suggesting a hot spot (cluster of high values). Conversely, negative Gi\\* values indicate that a feature has low values and is surrounded by other features with similarly low values, suggesting a cold spot (cluster of low values).\n\nWhen comparing to the previous Local Moran's I analysis, we can see that the most significant cold spot coincides with the most significant low-low cluster previously. This could suggest that the results from the two analyses are consistent since they both reinforce the spatial pattern of low values in the north-western areas.\n\n# Emerging Hotspot Analysis\n\nEmerging Hot Spot Analysis, also known as Space-Time Pattern Mining, is a sophisticated spatial analysis technique used to identify and analyze the emergence of hot spots or clusters of events over both space and time. This analysis provides valuable insights into the temporal dynamics of spatial phenomena.\n\n## Creating a Time Series Cube\n\nA space-time cube is a conceptual representation used in spatio-temporal analysis to visualize and analyze spatio-temporal data.\n\nIt is a three-dimensional construct that integrates spatial and temporal dimensions:\n\n-   Spatial dimension of the space-time cube represents the geographic extent or area under study\n\n-   Temporal dimension of the space-time cube represents time, typically divided into discrete time intervals or periods\n\n-   Data observations are organized and stored in a structured format that reflects both the spatial and temporal dimensions\n\n### Data Preparation\n\nIn order to create the space-time cube, two input objects are required:\n\n1.  Sf tibble data table that includes a geometry column (polygon feature class)\n\n2.  Aspatial tibble data frame that includes at least 3 columns, one for temporal, one for the unique ID and one for observation values\n\nWe aim to construct a spatio-temporal framework spanning from week 31 to week 50, hence we want to group our previously joined and cleaned data, tainan_dengue, by TOWNVILL and week. Get the sum of dengue cases in each village per week by using `sum()`is used to sum up the values of the variable `確定病例數`\n\nSince this is the aspatial data input, we can use st_drop_geometry() to drop the geometry column from the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_VILLWEEK <- tainan_dengue %>%\n  group_by(week, TOWNVILL) %>%\n  summarise(total_cases = sum(確定病例數)) %>%\n  st_drop_geometry()\n```\n:::\n\n\nGiven a number of spatial features n, and time periods m, a spatio-temporal full grid contains *n x m* rows. Each location has a recorded observation for each of the time periods in m. For example, if there are 10 locations and 20 time periods, there are 20 observations per location meaning there are 10 x 20 = 200 observations. This is efficient only when are there are complete time-series for each location.\n\n![](images/clipboard-2515252264.png)\n\nThe tn_counties data that we prepared earlier shows that there are 258 villages in our analysis.\n\nThis means that our full grid should contain 258 x 20 (weeks) = 5160 rows of data. Each row represents a unique combination of village and week, with observations or measurements recorded for each village across all 20 weeks. However, currently the dengue_VILLWEEK data only consists of 3082 rows, which suggests that the time series is incomplete.\n\n![](images/clipboard-2933050198.png)\n\nWhen we inspect the dengue_VILLWEEK data, we can see that there are some TOWNVILL rows that have missing week and total_cases values. This is because in the dataset for dengue cases, there are no records for dengue cases in these TOWNVILL. We can also see that the existing TOWNVILL data could also have missing week rows. Thus, we have to use the code below to insert the rows for missing weeks of each TOWNVILL and insert the total_cases as 0. This also inserts the week and total_cases data for the rows that have missing values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get unique TOWNVILL values\nunique_TOWNVILL <- unique(dengue_VILLWEEK$TOWNVILL)\n\n# Loop through each unique TOWNVILL value\nfor (town_vill in unique_TOWNVILL) {\n  # Subset dengue_VILLWEEK for the current TOWNVILL\n  subset_joinMe <- dengue_VILLWEEK[dengue_VILLWEEK$TOWNVILL == town_vill, ]\n  \n  # Get unique weeks within the subset\n  unique_weeks <- unique(subset_joinMe$week)\n  \n  # Create a vector of all weeks from 31 to 50\n  all_weeks <- 31:50\n  \n  # Find missing weeks\n  missing_weeks <- setdiff(all_weeks, unique_weeks)\n  \n  # Add rows for missing weeks with total_cases as 0\n  for (week in missing_weeks) {\n    new_row <- data.frame(TOWNVILL = town_vill,\n                          week = week,\n                          total_cases = 0)\n    dengue_VILLWEEK <- rbind(dengue_VILLWEEK, new_row)\n  }\n}\n\n  #Drop extra rows that had null values\ndengue_VILLWEEK <- na.omit(dengue_VILLWEEK)\n```\n:::\n\n\n![](images/clipboard-1505017461.png)\n\nNow we have 5160 observations! We can now convert this table into a tibble dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_VILLWEEK <- as_tibble(dengue_VILLWEEK)\n```\n:::\n\n\n### Create Space Time Cube\n\nIn the code chunk below, [`spacetime()`](https://sfdep.josiahparry.com/reference/spacetime.html) of sfdep is used to create an spatio-temporal cube. `is_spacetime_cube()` of sfdep package will be used to varify if tainan_st is indeed a space-time cube object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntainan_st <- spacetime(.data = dengue_VILLWEEK, .geo = tn_counties, \"TOWNVILL\", \"week\")\n\nis_spacetime_cube(tainan_st)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n\nThe **TRUE** return confirms that tainan_st object is indeed a space-time cube.\n\n## Computing Gi\\*\n\nWe should compute the Gi\\* to identify locations that exhibit significant spatial patterns.\n\n### Deriving the Spatial Weights\n\nThe code chunk below will be used to identify neighbors and to derive an inverse distance weights.\n\n-   `activate()` of dplyr package is used to activate the geometry context\n\n-   `mutate()` of dplyr package is used to create two new columns *nb* and *wt*.\n\n-   Then we will activate the data context again and copy over the nb and wt columns to each time-slice using `set_nbs()` and `set_wts()`\n\n    -   row order is very important so do not rearrange the observations after using `set_nbs()` or `set_wts()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue_nb <- tainan_st %>%\n  activate(\"geometry\") %>%\n  mutate(nb = include_self(st_contiguity(geometry)),\n         wt = st_inverse_distance(nb, geometry,\n                                  scale = 1,\n                                  alpha = 1),\n         .before = 1) %>%\n  set_nbs(\"nb\") %>%\n  set_wts(\"wt\")\n```\n:::\n\n\nNote that this dataset now has neighbors and weights for each time-slice.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(dengue_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n   week TOWNVILL      total_cases nb        wt       \n  <dbl> <chr>               <dbl> <list>    <list>   \n1    31 安南區_青草里           0 <int [4]> <dbl [4]>\n2    31 仁德區_保安里           1 <int [6]> <dbl [6]>\n3    31 中西區_赤嵌里           0 <int [9]> <dbl [9]>\n4    31 南區_大成里             0 <int [7]> <dbl [7]>\n5    31 安南區_城北里           0 <int [5]> <dbl [5]>\n6    31 安南區_城南里           0 <int [8]> <dbl [8]>\n```\n:::\n:::\n\n\n### Gi\\*\n\nWe can use these new columns to manually calculate the local Gi\\* for each location. We can do this by grouping by *week* and using `local_gstar_perm()` of sfdep package. After which, we `use unnest()` to unnest *gi_star* column of the newly created *gi_starts* data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngi_stars <- dengue_nb %>% \n  group_by(week) %>% \n  mutate(gi_star = local_gstar_perm(\n    total_cases, nb, wt)) %>% \n  tidyr::unnest(gi_star)\n```\n:::\n\n\n## Mann-Kendall Test\n\nThe Mann-Kendall test is a non-parametric statistical test used to detect trends in time series data. It evaluates the statistical significance of trends in time series data by comparing the observed values with expected values under the null hypothesis of no trend.\n\nThe hypotheses we are testing are:\n\n1.  Null hypothesis (H0): There is no trend present in the time series data.\n\n2.  Alternative hypothesis (H1): The data points are not randomly distributed but exhibit a consistent increase or decrease over time.\n\nIf the p-value associated with the test statistic is less than the chosen significance level (e.g., 0.05 or 0.01), we reject the null hypothesis, concluding that there is a statistically significant trend present in the data. If the p-value is greater than the significance level, we fail to reject the null hypothesis, suggesting that there is no significant trend in the data. In the output, sl is the p-value.\n\nWith these Gi\\* measures we can evaluate each location for a trend using the Mann-Kendall test. The locations I chose to evaluate are the hot and cold spots that are statistically significant, which we derived from our previous HCSA. I loaded the Tainan shapefile into QGIS to identify their town and village names.\n\n![](images/clipboard-866569547.png){width=\"412\"}\n\n![](images/clipboard-1313544634.png){width=\"413\"}\n\n![](images/clipboard-2864467401.png){width=\"412\"}\n\n![](images/clipboard-1394964883.png){width=\"412\"}\n\n::: panel-tabset\n## 安南區_顯宮里 (COLD)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg1 <- gi_stars %>% \n  ungroup() %>% \n  filter(TOWNVILL == \"安南區_顯宮里\") |> \n  select(TOWNVILL, week, gi_star)\n\np <- ggplot(data = cbg1, \n       aes(x = week, \n           y = gi_star)) +\n  geom_line() +\n  theme_light()\n\nggplotly(p)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-e2ecedf8c1e4e9e0fe9e\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e2ecedf8c1e4e9e0fe9e\">{\"x\":{\"data\":[{\"x\":[31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],\"y\":[-1.1932711935852198,-1.5185194584608479,-1.5298744463386391,-1.4749148038781861,-1.8829483066154469,-2.1112891337134574,-2.3174709977508763,-2.6359222556916921,-2.6287450510335617,-2.7947303975363376,-2.9419378941614625,-2.4650003973627865,-2.4686779581639939,-2.503699034859455,-2.2538173704495925,-2.465256598589074,-1.67344224770018,-1.5429313937825848,-1.6361490077344261,-0.52591909855919039],\"text\":[\"week: 31<br />gi_star: -1.1932712\",\"week: 32<br />gi_star: -1.5185195\",\"week: 33<br />gi_star: -1.5298744\",\"week: 34<br />gi_star: -1.4749148\",\"week: 35<br />gi_star: -1.8829483\",\"week: 36<br />gi_star: -2.1112891\",\"week: 37<br />gi_star: -2.3174710\",\"week: 38<br />gi_star: -2.6359223\",\"week: 39<br />gi_star: -2.6287451\",\"week: 40<br />gi_star: -2.7947304\",\"week: 41<br />gi_star: -2.9419379\",\"week: 42<br />gi_star: -2.4650004\",\"week: 43<br />gi_star: -2.4686780\",\"week: 44<br />gi_star: -2.5036990\",\"week: 45<br />gi_star: -2.2538174\",\"week: 46<br />gi_star: -2.4652566\",\"week: 47<br />gi_star: -1.6734422\",\"week: 48<br />gi_star: -1.5429314\",\"week: 49<br />gi_star: -1.6361490\",\"week: 50<br />gi_star: -0.5259191\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":37.260273972602747},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[30.050000000000001,50.950000000000003],\"tickmode\":\"array\",\"ticktext\":[\"35\",\"40\",\"45\",\"50\"],\"tickvals\":[35,40,45,50],\"categoryorder\":\"array\",\"categoryarray\":[\"35\",\"40\",\"45\",\"50\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"week\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-3.0627388339415762,-0.40511815877907675],\"tickmode\":\"array\",\"ticktext\":[\"-3\",\"-2\",\"-1\"],\"tickvals\":[-3,-2,-1],\"categoryorder\":\"array\",\"categoryarray\":[\"-3\",\"-2\",\"-1\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"8e7c165d2ec\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"8e7c165d2ec\",\"visdat\":{\"8e7c165d2ec\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg1 %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n      tau    sl     S     D  varS\n    <dbl> <dbl> <dbl> <dbl> <dbl>\n1 -0.0947 0.581   -18  190.   950\n```\n:::\n:::\n\n\nSince sl is much greater than the significance level of 0.05, we fail to reject the null hypothesis, suggesting that there is no significant trend in the data.\n\n## 安南區_砂崙里 (COLD)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg2 <- gi_stars %>% \n  ungroup() %>% \n  filter(TOWNVILL == \"安南區_砂崙里\") |> \n  select(TOWNVILL, week, gi_star)\n\np <- ggplot(data = cbg2, \n       aes(x = week, \n           y = gi_star)) +\n  geom_line() +\n  theme_light()\n\nggplotly(p)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-56ded1fcbf305623a1ac\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-56ded1fcbf305623a1ac\">{\"x\":{\"data\":[{\"x\":[31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],\"y\":[-0.87250243048539888,-1.1103192010072103,-1.0613180879946738,-1.1342061134021377,-1.6193669076845798,-1.7040536712088918,-1.7097602516263357,-2.1399238747808158,-1.9948514431053572,-2.202584938512369,-2.2517435379066186,-1.9220109947496005,-2.0535293498306531,-1.9857075979408496,-2.0841632706623536,-1.505514998003942,-1.5320360381836888,-0.89738264439601911,-1.196328205657476,0.02073523438804117],\"text\":[\"week: 31<br />gi_star: -0.87250243\",\"week: 32<br />gi_star: -1.11031920\",\"week: 33<br />gi_star: -1.06131809\",\"week: 34<br />gi_star: -1.13420611\",\"week: 35<br />gi_star: -1.61936691\",\"week: 36<br />gi_star: -1.70405367\",\"week: 37<br />gi_star: -1.70976025\",\"week: 38<br />gi_star: -2.13992387\",\"week: 39<br />gi_star: -1.99485144\",\"week: 40<br />gi_star: -2.20258494\",\"week: 41<br />gi_star: -2.25174354\",\"week: 42<br />gi_star: -1.92201099\",\"week: 43<br />gi_star: -2.05352935\",\"week: 44<br />gi_star: -1.98570760\",\"week: 45<br />gi_star: -2.08416327\",\"week: 46<br />gi_star: -1.50551500\",\"week: 47<br />gi_star: -1.53203604\",\"week: 48<br />gi_star: -0.89738264\",\"week: 49<br />gi_star: -1.19632821\",\"week: 50<br />gi_star:  0.02073523\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":48.949771689497723},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[30.050000000000001,50.950000000000003],\"tickmode\":\"array\",\"ticktext\":[\"35\",\"40\",\"45\",\"50\"],\"tickvals\":[35,40,45,50],\"categoryorder\":\"array\",\"categoryarray\":[\"35\",\"40\",\"45\",\"50\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"week\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-2.3653674765213517,0.13435917300277417],\"tickmode\":\"array\",\"ticktext\":[\"-2.0\",\"-1.5\",\"-1.0\",\"-0.5\",\"0.0\"],\"tickvals\":[-2,-1.5,-1,-0.5,0],\"categoryorder\":\"array\",\"categoryarray\":[\"-2.0\",\"-1.5\",\"-1.0\",\"-0.5\",\"0.0\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"8e7c23d74ac8\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"8e7c23d74ac8\",\"visdat\":{\"8e7c23d74ac8\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg2 %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n      tau    sl     S     D  varS\n    <dbl> <dbl> <dbl> <dbl> <dbl>\n1 -0.0842 0.626   -16  190.   950\n```\n:::\n:::\n\n\nSince sl is much greater than the significance level of 0.05, we fail to reject the null hypothesis, suggesting that there is no significant trend in the data.\n\n## 安南區_大安里 (HOT)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg3 <- gi_stars %>% \n  ungroup() %>% \n  filter(TOWNVILL == \"安南區_大安里\") |> \n  select(TOWNVILL, week, gi_star)\n\np <- ggplot(data = cbg3, \n       aes(x = week, \n           y = gi_star)) +\n  geom_line() +\n  theme_light()\n\nggplotly(p)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-0610e247e5c0adfbea84\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-0610e247e5c0adfbea84\">{\"x\":{\"data\":[{\"x\":[31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],\"y\":[0.76664124654249277,3.5477197771765532,3.7146434593513038,7.6098375771557558,6.4589889782814218,7.6204001006944999,6.8322784100934992,6.266154688675436,1.3629288297719797,1.9454210088711108,1.5274922658770336,0.69467947452790868,3.6004508370606318,1.8960272359400652,1.8183741858431612,0.49348200085321792,-1.1909036366080343,2.0222046293149067,-0.887127760572475,-0.3406386413577957],\"text\":[\"week: 31<br />gi_star:  0.7666412\",\"week: 32<br />gi_star:  3.5477198\",\"week: 33<br />gi_star:  3.7146435\",\"week: 34<br />gi_star:  7.6098376\",\"week: 35<br />gi_star:  6.4589890\",\"week: 36<br />gi_star:  7.6204001\",\"week: 37<br />gi_star:  6.8322784\",\"week: 38<br />gi_star:  6.2661547\",\"week: 39<br />gi_star:  1.3629288\",\"week: 40<br />gi_star:  1.9454210\",\"week: 41<br />gi_star:  1.5274923\",\"week: 42<br />gi_star:  0.6946795\",\"week: 43<br />gi_star:  3.6004508\",\"week: 44<br />gi_star:  1.8960272\",\"week: 45<br />gi_star:  1.8183742\",\"week: 46<br />gi_star:  0.4934820\",\"week: 47<br />gi_star: -1.1909036\",\"week: 48<br />gi_star:  2.0222046\",\"week: 49<br />gi_star: -0.8871278\",\"week: 50<br />gi_star: -0.3406386\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":31.415525114155255},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[30.050000000000001,50.950000000000003],\"tickmode\":\"array\",\"ticktext\":[\"35\",\"40\",\"45\",\"50\"],\"tickvals\":[35,40,45,50],\"categoryorder\":\"array\",\"categoryarray\":[\"35\",\"40\",\"45\",\"50\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"week\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-1.6314688234731611,8.0609652875596272],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"2\",\"4\",\"6\",\"8\"],\"tickvals\":[0,2,4,6,8],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"2\",\"4\",\"6\",\"8\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"8e7c7b0d69f\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"8e7c7b0d69f\",\"visdat\":{\"8e7c7b0d69f\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg3 %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n     tau      sl     S     D  varS\n   <dbl>   <dbl> <dbl> <dbl> <dbl>\n1 -0.453 0.00582   -86  190.   950\n```\n:::\n:::\n\n\nThe sl value here is much smaller but it is still greater than the significance level of 0.05. This tells us there is a downward but insignificant trend.\n\n## 永康區_東橋里 (HOT)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg4 <- gi_stars %>% \n  ungroup() %>% \n  filter(TOWNVILL == \"永康區_東橋里\") |> \n  select(TOWNVILL, week, gi_star)\n\np <- ggplot(data = cbg4, \n       aes(x = week, \n           y = gi_star)) +\n  geom_line() +\n  theme_light()\n\nggplotly(p)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-ee62540afc6183ec2409\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ee62540afc6183ec2409\">{\"x\":{\"data\":[{\"x\":[31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],\"y\":[4.6049636246470538,5.227721458033737,3.2664295719896455,2.3006187620324798,1.1503436386366757,2.5275089553073022,1.1885835546579884,1.3714105046077045,1.1397447184461413,0.20355983982055317,0.80615204766359416,1.0692576592450487,1.3738518063163321,1.0585492242971963,1.0946857204367952,0.27693541191335974,0.64665013088951739,0.35086641590298534,1.5617785982919521,1.4694798342095023],\"text\":[\"week: 31<br />gi_star: 4.6049636\",\"week: 32<br />gi_star: 5.2277215\",\"week: 33<br />gi_star: 3.2664296\",\"week: 34<br />gi_star: 2.3006188\",\"week: 35<br />gi_star: 1.1503436\",\"week: 36<br />gi_star: 2.5275090\",\"week: 37<br />gi_star: 1.1885836\",\"week: 38<br />gi_star: 1.3714105\",\"week: 39<br />gi_star: 1.1397447\",\"week: 40<br />gi_star: 0.2035598\",\"week: 41<br />gi_star: 0.8061520\",\"week: 42<br />gi_star: 1.0692577\",\"week: 43<br />gi_star: 1.3738518\",\"week: 44<br />gi_star: 1.0585492\",\"week: 45<br />gi_star: 1.0946857\",\"week: 46<br />gi_star: 0.2769354\",\"week: 47<br />gi_star: 0.6466501\",\"week: 48<br />gi_star: 0.3508664\",\"week: 49<br />gi_star: 1.5617786\",\"week: 50<br />gi_star: 1.4694798\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":31.415525114155255},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[30.050000000000001,50.950000000000003],\"tickmode\":\"array\",\"ticktext\":[\"35\",\"40\",\"45\",\"50\"],\"tickvals\":[35,40,45,50],\"categoryorder\":\"array\",\"categoryarray\":[\"35\",\"40\",\"45\",\"50\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"week\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.047648241090106042,5.4789295389443966],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"],\"tickvals\":[0,1,2,3,3.9999999999999996,5],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"8e7c6dc24700\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"8e7c6dc24700\",\"visdat\":{\"8e7c6dc24700\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg4 %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n     tau      sl     S     D  varS\n   <dbl>   <dbl> <dbl> <dbl> <dbl>\n1 -0.442 0.00708   -84  190.   950\n```\n:::\n:::\n\n\nThe sl value here is greater than the significance level of 0.05. This tells us there is a downward but insignificant trend.\n:::\n\nWe can replicate this for each location by using group_by() of dplyr package. The code below performs the Mann-Kendall test for each location in the dataset, allowing for the assessment of trends in the spatial data at a local level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa <- gi_stars %>%\n  group_by(TOWNVILL) %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>%\n  tidyr::unnest_wider(mk)\n```\n:::\n\n\n### Arrange to show significant emerging hot/cold spots\n\nThe code below arranges the ehsa dataframe base of the 'sl' and 'tau' values. This is to prioritize locations with significant trends and stronger associations. Then use the slice() functions to select the top 5 rows, which are the top 5 locations with the most significant emerging hot/cold spots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemerging <- ehsa %>% \n  arrange(sl, abs(tau)) %>% \n  slice(1:5)\n```\n:::\n\n\n### Performing Emerging Hotspot Analysis\n\nLastly, we will perform EHSA analysis by using emerging_hotspot_analysis() of sfdep package.\n\n-   It takes a spacetime object x (i.e. tainan_st), and the quoted name of the variable of interest (i.e. total_cases) for .var argument.\n\n-   The k argument is used to specify the number of time lags which is set to 1 by default.\n\n-   Lastly, nsim map numbers of simulation to be performed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa <- emerging_hotspot_analysis(\n  x = tainan_st, \n  .var = \"total_cases\", \n  k = 1, \n  nsim = 99\n)\n```\n:::\n\n\n### **Visualising the distribution of EHSA classes**\n\nIn the code chunk below, ggplot2 functions ised used to reveal the distribution of EHSA classes as a bar chart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = ehsa, aes(x = classification)) +\n  geom_bar() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\nThe figure above shows that oscillating hotspot has the highest numbers of villages.\n\nThis means that the spatial pattern of the occurrence of dengue cases varies periodically or cyclically over time. In the case of dengue fever, it can result in an oscillating hotspot due to various factors that affect the dynamics of dengue transmission. One highly plausible reason could be climatic factors, causing dengue fever transmission to occur more during hot, humid weather with heavy rainfall.\n\n### Visualising EHSA\n\nIn order to visualise the geographic distribution of EHSA classes, we need to join tn_counties and ehsa together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntainan_ehsa <- tn_counties %>%\n  left_join(ehsa,\n            by = join_by(TOWNVILL == location))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_sig <- tainan_ehsa  %>%\n  filter(p_value < 0.05)\ntmap_mode(\"plot\")\ntm_shape(tainan_ehsa) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(ehsa_sig) +\n  tm_fill(\"classification\") + \n  tm_borders(alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-67-1.png){width=672}\n:::\n:::\n\n\nFrom the map we can see that there are few areas that are oscillating coldspots as well, where the cases also fluctuates periodically but results in localized areas of lower dengue occurrences compared to surrounding areas.\n\nHowever, from the map we can also identify many areas that are sporadic hotspots, which have unusually high number of cases compared to neighbour but there are no clear trends. This can be due to localized characteristics or human behaviour, making it unpredictable.\n\n# Conclusion\n\nThorough analyses of hotspot patterns are important for strategic planning and optimizing resource distribution, not only in response to current challenges but also in anticipation of future outbreaks. By discerning the underlying spatial and temporal dynamics across various locations, stakeholders gain invaluable insights into effective intervention strategies and resource allocation frameworks.\n\nIn addition to our current analyses, further exploration can include an assessment of population density in each location and an examination of demographic factors that may render certain groups more susceptible to outbreaks. Moreover, on-the-ground data collection efforts can offer invaluable insights into location-specific environmental factors that may contribute to disease transmission. By identifying and addressing these factors, we can enhance preventive measures and improve our ability to respond effectively to emerging health threats.\n\n# References\n\n<https://www.cmmcp.org/mosquito-surveillance-data/pages/epi-week-calendars-2008-2024#:~:text=WHAT%20IS%20AN%20%22EPI%20WEEK,published%20them%20in%20the%20past>\n\n<https://pro.arcgis.com/en/pro-app/latest/tool-reference/spatial-statistics/h-how-spatial-autocorrelation-moran-s-i-spatial-st.htm>\n\n<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5876941/>\n\n<https://sfdep.josiahparry.com/articles/spacetime-s3.html>\n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\r\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\r\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\r\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}